CREATE TABLE `block_detail_info` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `block_hash` varchar(128) DEFAULT NULL,
  `block_height` bigint(20) DEFAULT NULL,
  `block_time_stamp` datetime(6) DEFAULT NULL,
  `depot_updatetime` datetime(6) DEFAULT NULL,
  `status` smallint(6) NOT NULL,
  `tx_count` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`pk_id`),
  UNIQUE KEY `UK_block_height` (`block_height`),
  KEY `block_hash` (`block_hash`),
  KEY `block_timestamp` (`block_time_stamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
 CREATE TABLE `block_raw_data` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `block_hash` varchar(128) DEFAULT NULL,
  `block_height` bigint(20) DEFAULT NULL,
  `block_time_stamp` datetime(6) DEFAULT NULL,
  `db_hash` varchar(255) DEFAULT NULL,
  `depot_updatetime` datetime(6) DEFAULT NULL,
  `extra_data` longtext,
  `gas_limit` varchar(255) DEFAULT NULL,
  `gas_used` varchar(255) DEFAULT NULL,
  `logs_bloom` longtext,
  `parent_hash` varchar(255) DEFAULT NULL,
  `receipts_root` varchar(255) DEFAULT NULL,
  `sealer` varchar(255) DEFAULT NULL,
  `sealer_list` longtext,
  `signature_list` longtext,
  `state_root` varchar(255) DEFAULT NULL,
  `transaction_list` longtext,
  `transactions_root` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`pk_id`),
  UNIQUE KEY `UK_block_height` (`block_height`),
  KEY `block_hash` (`block_hash`),
  KEY `block_timestamp` (`block_time_stamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
CREATE TABLE `block_task_pool` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `block_height` bigint(20) DEFAULT NULL,
  `certainty` smallint(6) DEFAULT NULL,
  `depot_updatetime` datetime(6) DEFAULT NULL,
  `handle_item` smallint(6) DEFAULT NULL,
  `sync_status` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`pk_id`),
  UNIQUE KEY `UK_block_height` (`block_height`),
  KEY `sync_status` (`sync_status`),
  KEY `certainty` (`certainty`),
  KEY `depot_updatetime` (`depot_updatetime`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
CREATE TABLE `block_tx_detail_info` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `block_hash` varchar(255) DEFAULT NULL,
  `block_height` bigint(20) DEFAULT NULL,
  `block_time_stamp` datetime(6) DEFAULT NULL,
  `contract_name` varchar(255) DEFAULT NULL,
  `depot_updatetime` datetime(6) DEFAULT NULL,
  `method_name` varchar(255) DEFAULT NULL,
  `tx_from` varchar(255) DEFAULT NULL,
  `tx_hash` varchar(255) DEFAULT NULL,
  `tx_to` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`pk_id`),
  KEY `block_height` (`block_height`),
  KEY `block_timestamp` (`block_time_stamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
CREATE TABLE `deployed_account_info` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `abi_hash` varchar(128) DEFAULT NULL,
  `block_height` bigint(20) DEFAULT NULL,
  `block_time_stamp` datetime(6) DEFAULT NULL,
  `contract_address` varchar(128) DEFAULT NULL,
  `contract_name` varchar(255) DEFAULT NULL,
  `depot_updatetime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`pk_id`),
  KEY `block_height` (`block_height`),
  KEY `contract_address` (`contract_address`),
  KEY `block_timestamp` (`block_time_stamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
CREATE TABLE `tx_receipt_raw_data` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `block_hash` varchar(128) DEFAULT NULL,
  `block_height` bigint(20) DEFAULT NULL,
  `block_time_stamp` datetime(6) DEFAULT NULL,
  `contract_address` varchar(255) DEFAULT NULL,
  `depot_updatetime` datetime(6) DEFAULT NULL,
  `from` varchar(255) DEFAULT NULL,
  `gas_used` varchar(255) DEFAULT NULL,
  `input` longtext,
  `logs` longtext,
  `logs_bloom` longtext,
  `message` varchar(255) DEFAULT NULL,
  `output` longtext,
  `receipt_proof` longtext,
  `root` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `to` varchar(255) DEFAULT NULL,
  `tx_hash` varchar(255) DEFAULT NULL,
  `tx_index` varchar(255) DEFAULT NULL,
  `tx_proof` longtext,
  PRIMARY KEY (`pk_id`),
  KEY `block_hash` (`block_hash`),
  KEY `block_timestamp` (`block_time_stamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
CREATE TABLE `tx_raw_data` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `block_hash` varchar(128) DEFAULT NULL,
  `block_height` bigint(20) DEFAULT NULL,
  `block_time_stamp` datetime(6) DEFAULT NULL,
  `depot_updatetime` datetime(6) DEFAULT NULL,
  `from` varchar(255) DEFAULT NULL,
  `gas` varchar(255) DEFAULT NULL,
  `gas_price` varchar(255) DEFAULT NULL,
  `input` longtext,
  `nonce` varchar(255) DEFAULT NULL,
  `to` varchar(255) DEFAULT NULL,
  `tx_hash` varchar(255) DEFAULT NULL,
  `tx_index` varchar(255) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`pk_id`),
  KEY `block_hash` (`block_hash`),
  KEY `block_timestamp` (`block_time_stamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
CREATE TABLE `contract_info` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `abi_hash` varchar(128) DEFAULT NULL,
  `contract_abi` longtext,
  `contract_binary` longtext,
  `contract_name` varchar(255) DEFAULT NULL,
  `depot_updatetime` datetime(6) DEFAULT NULL,
  `version` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`pk_id`),
  UNIQUE KEY `abi_hash` (`abi_hash`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
